[32mINFO    [0m testcase:base_api.py:43 {
  "errcode": 60112,
  "errmsg": "invalid name, hint: [1622035925_147_93679a5736efa1053e30466fc2e5b152], from ip: 113.116.140.163, more info at https://open.work.weixin.qq.com/devtool/query?e=60112"
}