{"name": "test_div_exception[get_div_exception_data2]", "status": "passed", "parameters": [{"name": "get_div_exception_data", "value": "[1, 0, 'ZeroDivisionError', 'division by zero']"}], "start": 1618301941499, "stop": 1618301941499, "uuid": "4bd58cfb-b17d-464e-bfab-ebe3b1fc61e5", "historyId": "c596a3d4adb98d366771867d35dd27b2", "testCaseId": "e2ca8cb1f8d27b002a03b922fca102ee", "fullName": "homework_test.test_2th_work.TestCalculator#test_div_exception", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "计算器除法异常场景用例"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_function')"}, {"name": "tag", "value": "run(order=5)"}, {"name": "parentSuite", "value": "homework_test"}, {"name": "suite", "value": "test_2th_work"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "ShimmerShiningHoon"}, {"name": "thread", "value": "11432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework_test.test_2th_work"}]}