{"name": "test_add_exception[add-1-a-TypeError-unsupported operand type(s) for +]", "status": "passed", "parameters": [{"name": "func", "value": "<bound method Calculator.add of <homework_test.test_1th_work.Calculator object at 0x000002383184A0C8>>"}, {"name": "a", "value": "1"}, {"name": "b", "value": "'a'"}, {"name": "exception", "value": "'TypeError'"}, {"name": "ex_pattern", "value": "'unsupported operand type(s) for +'"}], "start": 1618023589676, "stop": 1618023589676, "uuid": "c4739880-7e0b-4806-bc41-1ff7f9007025", "historyId": "067a3c52e6bb50979c981b79e68419b1", "testCaseId": "4dc9812b0cdd469f2c0110e8c1bd680c", "fullName": "homework_test.test_1th_work.TestCalculator#test_add_exception", "labels": [{"name": "story", "value": "计算器加法异常场景用例"}, {"name": "feature", "value": "计算器模块"}, {"name": "parentSuite", "value": "homework_test"}, {"name": "suite", "value": "test_1th_work"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "ShimmerShiningHoon"}, {"name": "thread", "value": "6720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework_test.test_1th_work"}]}